### ISSUE TITLE
Erro: App URI não instalado

### ISSUE THREAD

**Issue by gabrielferreir** [DeveloperCielo/LIO-Hybrid-Integration-Sample-Flutter#3]
Estou recebendo a mensagem "Erro: App URI não instalado", já tenho o emulador que disponibilizam na doc instalado.

[https://developercielo.github.io/manual/cielo-lio#integra%C3%A7%C3%A3o-local](url)

Preciso instalar outro?

**Comment by Astolfoho** [comment]
vc precisa abrir um chamado na cielo pedindo para eles instalarem o UriAppClient  na sua Lio
