### ISSUE TITLE
App URI não instalado

### ISSUE THREAD

**Issue by JacksonMonteiro** [DeveloperCielo/LIO-Hybrid-Integration-Sample-Flutter#4]
Olá, @mariofelesdossantosjunior, @eduardovianna e @moraisigor! 

Encontrei recentemente esta biblioteca de vocês, que realiza uma integração com LIO utilizando Flutter, e no início dos testes me deparei com o seguinte problema, que não consegui resolver até o momento: 

![image](https://user-images.githubusercontent.com/54756984/204602608-eda26e04-b36b-44d6-bc44-ebadaa3580bd.png)

Gostaria de saber, como faço para resolvê-lo para poder testar o repositório! Muito obrigado por lerem até aqui 👀✔

**Comment by StenioCamargo** [comment]
Encontrei isso na documentação deles 
"Atenção: Para que seja possível integrar de forma híbrida o nosso time de Suporte a Desenvolvedores precisa enviar o aplicativo UriAppClient para a LIO. Para isso, [Abra um ticket](https://devcielo.zendesk.com/hc/pt-br/requests/new?ticket_form_id=360000201671) em nossa ferramenta de atendimento."

**Comment by JacksonMonteiro** [comment]
Obrigado! Conversei com o suporte deles e essa solução que propus só pode ser testada na maquininha da Cielo. Optei por fazer um platformChannel no Flutter com Kotlin para conseguir testar no emulador e na maquininha! Obrigado Stenio
